improve video generation (#45)
* travis: install required Ubuntu packages

Fix:

No package 'gobject-introspection-1.0' found

ValueError: Namespace Gdk not available
ValueError: Namespace Gtk not available

* travis: run setup.py build

Compile fract4dc, fixes:

ImportError: cannot import name 'fract4dc' from 'fract4d'

* travis: set no-build-isolation pip option

From:
https://github.com/pypa/pip/issues/5229

To avoid failure with Python 3.6:

 Downloading
https://files.pythonhosted.org/packages/c1/36/c31a6ce9411b22a8ac0759c9b5ffda09368d5e0643450bb8ed83c271588c/PyGObject-3.32.1.tar.gz
(698kB) Could not find a version that satisfies the requirement pycairo
(from versions: ) No matching distribution found for pycairo

* travis: xvfb-run not required if using xenial and services: xvfb

https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-services

* skip test.py testGenerateMandelbrot() if $HOME is not set

Failing on Travis with:

A fatal error occurred:
	Error reported by C compiler:gcc: error:
/.gnofract4d-cache/fract4d_fdb3a0a1770dffc62e4964c804e32688.c: No such
file or directory

* tidy fractal.py

Mainly whitespace with some other no effect changes.

* DirectorDialog: fix broken Keyframe stopped spinbutton

Typo made in commit:
95cb196 ("more GTK+3 object conversion", 2018-02-01)

* use dedicated temporary directory in test_animation.py and test_director.py

* fix high CPU usage after video created

* fix video creation dialog not closed if video converter does not exist

* improve video generation

Speed up by removing Python threading and solely using the signals
emitted by gtkfractal.

Clarify that a video is made up of keyframes and transitions
consisting of a number of frames defined by the duration parameter.
By default the keyframe is shown for one frame but this is
configurable using the stopped parameter.

Co-authored-by: Edwin Young <edwin@bathysphere.org>